#!/home/lemmy/lemmy-blog/.venv/bin/python
"""
Create a complete blog post for Lemmy's Mic.

This script handles the full pipeline:
1. Generate post content (markdown)
2. Generate hero image (via Gemini)
3. Save files to correct locations
4. Optionally commit and push to deploy

Usage:
    python create_post.py --title "Post Title" --topic indie-games --scene "Description for hero image"

For use by Claude/Lemmy bot - call functions directly or via CLI.
"""

import argparse
import os
import re
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional

# Blog root directory
BLOG_ROOT = Path(__file__).parent.parent
CONTENT_DIR = BLOG_ROOT / "content" / "posts"
IMAGES_DIR = BLOG_ROOT / "static" / "images"

# Valid topics/tags
VALID_TAGS = [
    "indie-games",
    "e-bikes",
    "punk-music",
    "kava-bars",
    "ai-art",
    "tech",
    "meta"
]


def slugify(title: str) -> str:
    """Convert title to URL-friendly slug."""
    slug = title.lower()
    slug = re.sub(r'[^\w\s-]', '', slug)
    slug = re.sub(r'[-\s]+', '-', slug)
    return slug.strip('-')


def create_frontmatter(
    title: str,
    slug: str,
    tags: list[str],
    description: str,
    has_image: bool = True,
    draft: bool = False
) -> str:
    """Generate Hugo frontmatter."""
    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S-05:00")

    tags_str = ", ".join(f'"{t}"' for t in tags)
    image_line = f'image: "/images/hero-{slug}.png"' if has_image else ""

    return f'''---
title: "{title}"
date: {now}
draft: {str(draft).lower()}
tags: [{tags_str}]
{image_line}
description: "{description}"
---
'''


def create_post_file(
    title: str,
    content: str,
    tags: list[str],
    description: str,
    slug: Optional[str] = None,
    has_image: bool = True,
    draft: bool = False
) -> Path:
    """Create a new blog post markdown file."""
    slug = slug or slugify(title)

    frontmatter = create_frontmatter(title, slug, tags, description, has_image, draft)

    # Add FlowBoard attribution footer
    footer = """
---
*Generated by Lemmy using [FlowBoard](https://jweese001.github.io/flow-board/)*
"""

    full_content = frontmatter + "\n" + content + footer

    CONTENT_DIR.mkdir(parents=True, exist_ok=True)
    post_path = CONTENT_DIR / f"{slug}.md"

    with open(post_path, "w") as f:
        f.write(full_content)

    print(f"Created post: {post_path}")
    return post_path


def generate_hero_image(title: str, scene: str, slug: str) -> Optional[Path]:
    """Generate hero image using generate_hero.py script."""
    script_path = Path(__file__).parent / "generate_hero.py"

    try:
        result = subprocess.run(
            ["python3", str(script_path), title, scene, "--slug", slug],
            capture_output=True,
            text=True,
            timeout=180
        )

        if result.returncode == 0:
            image_path = IMAGES_DIR / f"hero-{slug}.png"
            if image_path.exists():
                return image_path
        else:
            print(f"Image generation failed: {result.stderr}")

    except subprocess.TimeoutExpired:
        print("Image generation timed out")
    except Exception as e:
        print(f"Image generation error: {e}")

    return None


def git_deploy(post_path: Path, image_path: Optional[Path], title: str) -> bool:
    """Commit and push changes to trigger Netlify deploy."""
    try:
        os.chdir(BLOG_ROOT)

        # Stage files
        files_to_add = [str(post_path)]
        if image_path and image_path.exists():
            files_to_add.append(str(image_path))

        subprocess.run(["git", "add"] + files_to_add, check=True)

        # Commit
        commit_msg = f"Add post: {title}"
        subprocess.run(["git", "commit", "-m", commit_msg], check=True)

        # Push
        subprocess.run(["git", "push"], check=True)

        print(f"Deployed: {title}")
        return True

    except subprocess.CalledProcessError as e:
        print(f"Git operation failed: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Create a Lemmy's Mic blog post")
    parser.add_argument("--title", required=True, help="Post title")
    parser.add_argument("--content", help="Post content (markdown). If not provided, creates placeholder.")
    parser.add_argument("--content-file", help="Read content from file")
    parser.add_argument("--tags", nargs="+", default=["tech"], help="Post tags")
    parser.add_argument("--description", help="SEO description (auto-generated if not provided)")
    parser.add_argument("--scene", help="Scene description for hero image")
    parser.add_argument("--slug", help="URL slug (auto-generated from title)")
    parser.add_argument("--no-image", action="store_true", help="Skip hero image generation")
    parser.add_argument("--draft", action="store_true", help="Create as draft")
    parser.add_argument("--deploy", action="store_true", help="Git commit and push after creation")

    args = parser.parse_args()

    # Validate tags
    for tag in args.tags:
        if tag not in VALID_TAGS:
            print(f"Warning: '{tag}' is not a standard tag. Valid tags: {VALID_TAGS}")

    slug = args.slug or slugify(args.title)

    # Get content
    if args.content_file:
        with open(args.content_file) as f:
            content = f.read()
    elif args.content:
        content = args.content
    else:
        content = f"## Introduction\n\nContent coming soon...\n\n## Main Section\n\n...\n\n## Conclusion\n\n..."

    # Generate description
    description = args.description or f"Lemmy's thoughts on {args.title.lower()}."

    # Generate hero image
    image_path = None
    if not args.no_image and args.scene:
        print(f"Generating hero image...")
        image_path = generate_hero_image(args.title, args.scene, slug)

    # Create post
    post_path = create_post_file(
        title=args.title,
        content=content,
        tags=args.tags,
        description=description,
        slug=slug,
        has_image=(image_path is not None or not args.no_image),
        draft=args.draft
    )

    # Deploy
    if args.deploy:
        git_deploy(post_path, image_path, args.title)
    else:
        print("\nTo deploy, run:")
        print(f"  cd {BLOG_ROOT} && git add -A && git commit -m 'Add post: {args.title}' && git push")


if __name__ == "__main__":
    main()
